import { nanoid } from 'nanoid'

/**
 * SVG ID Sanitization Utilities
 *
 * These functions help ensure SVG files have unique IDs before export,
 * preventing issues with duplicate IDs in downstream tools.
 */

export interface DuplicateIdReport {
  id: string
  count: number
  elements: Element[]
}

/**
 * Find all duplicate IDs in an SVG element
 */
export function findDuplicateIds(svgElement: SVGSVGElement): DuplicateIdReport[] {
  const idMap = new Map<string, Element[]>()

  // Collect all elements with IDs
  svgElement.querySelectorAll('[id]').forEach(el => {
    const id = el.getAttribute('id')!
    if (!idMap.has(id)) {
      idMap.set(id, [])
    }
    idMap.get(id)!.push(el)
  })

  // Filter to only duplicates
  const duplicates: DuplicateIdReport[] = []
  for (const [id, elements] of idMap) {
    if (elements.length > 1) {
      duplicates.push({ id, count: elements.length, elements })
    }
  }

  return duplicates
}

/**
 * Check if an SVG has any duplicate IDs
 */
export function hasDuplicateIds(svgElement: SVGSVGElement): boolean {
  return findDuplicateIds(svgElement).length > 0
}

/**
 * Sanitize duplicate IDs in an SVG by appending unique suffixes.
 * The first occurrence of each ID is kept as-is, subsequent occurrences
 * get a unique suffix appended.
 *
 * Also updates any internal references (url(#id), href="#id", xlink:href="#id")
 * to point to the new IDs.
 *
 * @param svgElement The SVG element to sanitize (modified in place)
 * @returns Number of IDs that were renamed
 */
export function sanitizeDuplicateIds(svgElement: SVGSVGElement): number {
  const duplicates = findDuplicateIds(svgElement)
  let renamedCount = 0

  for (const { id, elements } of duplicates) {
    // Keep the first element's ID, rename the rest
    for (let i = 1; i < elements.length; i++) {
      const newId = `${id}-${nanoid(6)}`
      const element = elements[i]

      // Update the element's ID
      element.setAttribute('id', newId)
      renamedCount++

      // Note: We don't update references because duplicate IDs shouldn't
      // have valid references anyway (they would be ambiguous)
    }
  }

  return renamedCount
}

/**
 * Remove all IDs from an SVG that match a pattern.
 * Useful for cleaning up auto-generated IDs before export.
 *
 * @param svgElement The SVG element to clean (modified in place)
 * @param pattern Regex pattern to match IDs to remove (default: /^(node-|svg-)/)
 * @returns Number of IDs removed
 */
export function removeAutoGeneratedIds(
  svgElement: SVGSVGElement,
  pattern: RegExp = /^(node-|svg-)/
): number {
  let removedCount = 0

  svgElement.querySelectorAll('[id]').forEach(el => {
    const id = el.getAttribute('id')!
    if (pattern.test(id)) {
      el.removeAttribute('id')
      removedCount++
    }
  })

  return removedCount
}

/**
 * Validate SVG IDs and return a report
 */
export interface SvgIdValidationReport {
  totalElements: number
  elementsWithIds: number
  uniqueIds: number
  duplicateIds: DuplicateIdReport[]
  autoGeneratedIds: number
  isValid: boolean
}

export function validateSvgIds(svgElement: SVGSVGElement): SvgIdValidationReport {
  const allElements = svgElement.querySelectorAll('*')
  const elementsWithIds = svgElement.querySelectorAll('[id]')
  const duplicates = findDuplicateIds(svgElement)

  let autoGeneratedCount = 0
  const uniqueIds = new Set<string>()

  elementsWithIds.forEach(el => {
    const id = el.getAttribute('id')!
    uniqueIds.add(id)
    if (/^(node-|svg-)/.test(id)) {
      autoGeneratedCount++
    }
  })

  return {
    totalElements: allElements.length,
    elementsWithIds: elementsWithIds.length,
    uniqueIds: uniqueIds.size,
    duplicateIds: duplicates,
    autoGeneratedIds: autoGeneratedCount,
    isValid: duplicates.length === 0
  }
}

/**
 * Prepare SVG for export by sanitizing IDs and optionally removing auto-generated ones
 *
 * @param svgElement The SVG element to prepare (modified in place)
 * @param options Configuration options
 * @returns Report of changes made
 */
export interface PrepareForExportOptions {
  /** Remove auto-generated IDs (node-*, svg-*) */
  removeAutoIds?: boolean
  /** Fix duplicate IDs by appending suffixes */
  fixDuplicates?: boolean
}

export interface PrepareForExportReport {
  duplicatesFixed: number
  autoIdsRemoved: number
  validation: SvgIdValidationReport
}

export function prepareForExport(
  svgElement: SVGSVGElement,
  options: PrepareForExportOptions = {}
): PrepareForExportReport {
  const { removeAutoIds = false, fixDuplicates = true } = options

  let duplicatesFixed = 0
  let autoIdsRemoved = 0

  // Fix duplicates first (before removing auto IDs)
  if (fixDuplicates) {
    duplicatesFixed = sanitizeDuplicateIds(svgElement)
  }

  // Optionally remove auto-generated IDs
  if (removeAutoIds) {
    autoIdsRemoved = removeAutoGeneratedIds(svgElement)
  }

  // Validate the result
  const validation = validateSvgIds(svgElement)

  return {
    duplicatesFixed,
    autoIdsRemoved,
    validation
  }
}
